language: objective-c
osx_image: xcode7.2
xcode_project: Pastel.xcodeproj
before_install:
  - brew update
  - brew upgrade xctool
  - brew install carthage
  - carthage bootstrap --verbose
xcode_scheme: Pastel
