language: objective-c
osx_image: xcode7.3
xcode_project: Pastel.xcodeproj
before_install:
  - brew install swiftlint
  - curl -OlL "https://github.com/Carthage/Carthage/releases/download/0.14/Carthage.pkg"
  - sudo installer -pkg "Carthage.pkg" -target /
  - rm "Carthage.pkg"
  - carthage version # Print version for debugging purposes
  - carthage bootstrap --platform osx --verbose
xcode_scheme: Pastel
